docker load < k8s.gcr.io_coredns_1.3.1.tar
docker load < k8s.gcr.io_etcd_3.3.10.tar
docker load < k8s.gcr.io_kube-apiserver_v1.15.3.tar
docker load < k8s.gcr.io_kube-controller-manager_v1.15.3.tar
docker load < k8s.gcr.io_kube-proxy_v1.15.3.tar
docker load < k8s.gcr.io_kube-scheduler_v1.15.3.tar
docker load < k8s.gcr.io_pause_3.1.tar
docker load < quay.io__kubernetes-ingress-controller_nginx-ingress-controller_0.26.1.tar
docker load < quay.io_coreos__flannel_v0.11.0-amd64.tar
